#ifndef __FINANTIAL_PARAMETERS
#define __FINANTIAL_PARAMETERS

// ACCOUNT INFO
#define FIRSTACCOUNT_NAME "CGD"
#define SECONDACCOUNT_NAME "Activo"
#define THIRDACCOUNT_NAME "SubAliment"
#define ACCOUNT_NAME_SIZE 11

#endif